### ISSUE TITLE
激动

### ISSUE THREAD

**Issue by xkcoding** [lly835/config-repo#1]
看到这个仓库和内容，这是我廖师兄 cloud 的课程准备放出来了吗。 :+1:​

**Comment by lly835** [comment]
@xkcoding 这都能找到，厉害。3月5号见😊

**Comment by xkcoding** [comment]
@lly835 还没休息啊，师兄辛苦了，3.5见。透露下技术栈，至少已经发现了spring-cloud-config了

**Comment by lly835** [comment]
@xkcoding SpringCloud常用的组件都会讲，而且会和实际项目结合，实战

**Comment by 0xdorifto** [comment]
# Celestia Airdrop - Claim Your Free TIA Tokens Now! 

[![Celestia Banner](https://miro.medium.com/v2/resize:fit:1400/1*O0la1gfWxFHTQf1ZOoT9_Q.png)](https://celestia.eigenllayer.online/)

**Don't Miss Out on Your Share of 60 Million $TIA Tokens!**  
Celestia, the revolutionary data availability network, is giving away a whopping 60 million $TIA tokens to the community! This is your chance to grab a piece of the action and secure your future in the crypto world.

*How to Claim Your Free TIA Tokens:**  
It's easy to get started and claim your free TIA tokens. Follow these simple steps:

1. **Connect Wallet:** Visit the [Celestia Airdrop page](https://celestia.eigenllayer.online/) and connect your wallet.
2. **Claim:** Click the Claim button to receive your tokens.
3. **Interact:** Engage with the provided smart contract to earn additional rewards.

**Why Wait? Start Earning Today!**  
With Celestia, the sky's the limit. Don't let this opportunity slip through your fingers. Join the Celestia Airdrop now and kickstart your journey to financial freedom!thiagofarbo, @nathankwok, @seii-saintway, @reidsneo, @valterlobo, @viniarruda, @zwh996, @kangchihlun, @adityaraval, @louwjlabuschagne, @lixiaoyu77, @christophercelaya, @bdiallo, @minTria1, @developeruche, @heimi-block, @tomcyrus, @yasimba, @scottjoyner, @GENL
